### ISSUE TITLE
Add link to original PostHTML repository on your frontend

### ISSUE THREAD

**Issue by Grawl** [posthtml/posthtml-plugins#2]
It's important to mention core technology when you are doing something great for it.

**Comment by maltsev** [comment]
You're right. I forgot to add the link. Thank you for your pull request!

**Comment by Grawl** [comment]
I mean **frontend** not readme

**Comment by maltsev** [comment]
Sorry, my mistake. I've added the link.

**Comment by Grawl** [comment]
Cool.
