### ISSUE TITLE
Change project URL to use HTTPS

### ISSUE THREAD

**Issue by maltsev** [posthtml/posthtml-plugins#22]
@awinogradov @Scrum @voischev can you please change the project URL in the repository header to https://... or grant me permissions to do that? 

![image](https://user-images.githubusercontent.com/923973/60009056-77fe3800-9675-11e9-92e2-684814f83346.png)

**Comment by Scrum** [comment]
@maltsev changed the rights, check

**Comment by maltsev** [comment]
Thanks, Ivan! I updated the URL.
