### ISSUE TITLE
Transfer

### ISSUE THREAD

**Issue by maltsev** [posthtml/posthtml-plugins#9]
@michael-ciniawsky @awinogradov what actions are required from me to transfer the plugins list to the [posthtml namespace](https://github.com/posthtml)?

**Comment by awinogradov** [comment]
Wait a moment:) We'll fix repo structure and readme when boilerplate will be ready. Then you can transfer it to posthtml org.

**Comment by Scrum** [comment]
@maltsev may be move this pkg to posthtml org ? and PR to readme ?

**Comment by maltsev** [comment]
@awinogradov has the repo structure and the readme been fixed?

**Comment by awinogradov** [comment]
I think yes. @voischev can we transfer it?

**Comment by voischev** [comment]
+1

**Comment by Scrum** [comment]
@maltsev transfer and add this readme please.

**Comment by maltsev** [comment]
I transferred the repository and now [the old URL](https://maltsev.github.io/posthtml-plugins/) isn't available anymore. I created [a new stub repository](https://github.com/maltsev/posthtml-plugins) with the redirect. It doesn't work, though. But let's wait for a few hours, maybe there is some cache.

@voischev or @awinogradov can you update the URL in [the repository description](https://github.com/posthtml/posthtml-plugins) (so `maltsev.github.io/..` → `posthtml.github.io/..`)?

@GitScrum which readme?

**Comment by Scrum** [comment]
> which readme?

@maltsev posthtml readme ) I suggest removing the entire section with plugins and replacing the description with yours http://posthtml.github.io/posthtml-plugins/ and I would suggest adding tags, links to examples (I'll post them soon, so far they are in my repository https://github.com/inside-demo), possibly categories

**Comment by maltsev** [comment]
Right. I'm totally for it. Would someone make those changes?

The redirect from [maltsev.github.io/posthtml-plugins/](http://maltsev.github.io/posthtml-plugins/) to [posthtml.github.io/posthtml-plugins/](http://posthtml.github.io/posthtml-plugins/) works fine, by the way.

**Comment by Scrum** [comment]
> Right. I'm totally for it. Would someone make those changes?

meybe you ?

**Comment by maltsev** [comment]
Sorry, I don't have time for that right now :-(

Besides replacing the section with a link to the plugins catalog we should also check that all plugins from that section are present also in the catalog.

**Comment by Scrum** [comment]
dont worry its ok )
